import type { SearchResult } from "./types.js";

/** Deterministic results for UI/filter tests and deploys without burning Jev. */
export const DEMO_RESULT: SearchResult = {
  question: "how do residual connections help train deep image networks?",
  sessionId: null,
  pending: 0,
  intent: {
    field: "cs",
    wantsReview: 0.21,
    wantsEmpirical: 0.18,
  },
  topics: [
    {
      id: "https://openalex.org/T11605",
      displayName: "Deep Learning Architectures",
      description: "Neural network designs including residual connections",
    },
  ],
  papers: [
    {
      id: "arxiv:1512.03385",
      title: "Deep Residual Learning for Image Recognition",
      abstract:
        "We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. Layers learn residual functions with reference to layer inputs.",
      year: 2016,
      venue: "CVPR",
      doi: "10.1109/cvpr.2016.90",
      url: "https://arxiv.org/abs/1512.03385",
      source: "arxiv",
      authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
      scored: true,
      method: 4,
      population: 4,
      evidence: 4,
      recency: 3,
      relevance: 0.98,
      isReview: 0.03,
      composite: 0.89,
    },
    {
      id: "oa:survey",
      title: "Deep Residual Learning for Image Recognition: A Survey",
      abstract:
        "This survey reviews residual networks, skip connections, and their use across computer vision benchmarks.",
      year: 2022,
      venue: "Applied Sciences",
      doi: "10.3390/app12188972",
      url: "https://doi.org/10.3390/app12188972",
      source: "openalex",
      scored: true,
      method: 4,
      population: 3.5,
      evidence: 3,
      recency: 4,
      relevance: 0.96,
      isReview: 0.97,
      composite: 0.86,
    },
    {
      id: "s2:inception",
      title:
        "Inception-v4, Inception-ResNet and the Impact of Residual Connections on Learning",
      abstract:
        "We study how residual connections change training dynamics of Inception networks.",
      year: 2017,
      venue: "AAAI",
      doi: null,
      url: "https://ojs.aaai.org/index.php/AAAI/article/view/11231",
      source: "semantic_scholar",
      scored: true,
      method: 4,
      population: 3.5,
      evidence: 3.5,
      recency: 3,
      relevance: 0.95,
      isReview: 0.04,
      composite: 0.84,
    },
    {
      id: "epmc:unet",
      title: "Recurrent residual U-Net for medical image segmentation",
      abstract:
        "A residual U-Net variant for biomedical segmentation tasks.",
      year: 2019,
      venue: "Journal of medical imaging",
      doi: "10.1117/1.jmi.6.1.014006",
      url: "https://doi.org/10.1117/1.jmi.6.1.014006",
      source: "europe_pmc",
      scored: true,
      method: 3,
      population: 2,
      evidence: 3,
      recency: 3,
      relevance: 0.73,
      isReview: 0.03,
      composite: 0.61,
    },
    {
      id: "rel:old",
      title: "Very Deep Convolutional Networks for Large-Scale Image Recognition",
      abstract:
        "We investigate the effect of convolutional network depth on accuracy.",
      year: 2015,
      venue: "ICLR",
      doi: null,
      url: "https://arxiv.org/abs/1409.1556",
      source: "related",
      scored: true,
      method: 2,
      population: 2.5,
      evidence: 2,
      recency: 2,
      relevance: 0.48,
      isReview: 0.02,
      composite: 0.42,
    },
    {
      id: "oa:undated",
      title: "Notes on skip connections",
      abstract: "Informal notes without a publication year.",
      year: null,
      venue: null,
      doi: null,
      url: null,
      source: "openalex",
      scored: true,
      method: 2,
      population: 2,
      evidence: 1,
      recency: 2,
      relevance: 0.36,
      isReview: 0.1,
      composite: 0.3,
    },
  ],
};
